# Generated by Django 4.2.15 on 2026-07-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('mbps', models.FloatField()),
                ('in_octets', models.BigIntegerField(blank=True, null=True)),
                ('out_octets', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('switch_ip', models.GenericIPAddressField()),
                ('switch_label', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_online', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('good', 'Good'), ('warn', 'Warning'), ('crit', 'Critical')], default='good', max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('sub', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=150)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('connection_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'Wi-Fi')], max_length=10)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('ap_label', models.CharField(blank=True, max_length=100)),
                ('link_speed_mbps', models.FloatField(blank=True, null=True)),
                ('upload_mbps', models.FloatField(blank=True, null=True)),
                ('download_mbps', models.FloatField(blank=True, null=True)),
                ('prev_in_octets', models.BigIntegerField(blank=True, null=True)),
                ('prev_out_octets', models.BigIntegerField(blank=True, null=True)),
                ('prev_sample_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Idle', 'Idle'), ('Inactive', 'Inactive')], default='Online', max_length=10)),
                ('is_authorized', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='monitor.lab')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new', 'New device'), ('unauthorized', 'Unauthorized device')], max_length=15)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.device')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
