# Generated by Django 4.2.15 on 2026-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('wifi_count', models.IntegerField(default=0)),
                ('ethernet_count', models.IntegerField(default=0)),
                ('lab_counts', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='peak_download_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='peak_upload_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
